### ISSUE TITLE
Exporter is not started when enable endToEnd

### ISSUE THREAD

**Issue by ggqshr** [cloudhut/kminion#112]
The docker image is quay.io/cloudhut/kminion:master
Use the configuration file below
```yaml
exporter:
  namespace: "kminion"
  host: "0.0.0.0"
  port: 9308
logger:
  # Valid values are: debug, info, warn, error, fatal, panic
  level: info
kafka:
  brokers: [kminion-monitoring-service:9093] 
  clientId: "kminion"
minion:
  consumerGroups:
    enabled: true
    scrapeMode: adminApi # Valid values: adminApi, offsetsTopic
    granularity: partition
    allowedGroups: [ ".*" ]
    ignoredGroups: [ ]
  topics:
    granularity: partition
    allowedTopics: [ ".*" ]
    ignoredTopics: [ ]
  logDirs:
    enabled: true
  endToEnd:
    enabled: true
    probeInterval: 1000ms
    topicManagement:
      enabled: true
      name: kminion-end-to-end
      reconciliationInterval: 10m
      replicationFactor: 1
      partitionsPerBroker: 1
    producer:
      ackSla: 5s
      requiredAcks: all
    consumer:
      groupIdPrefix: kminion-end-to-end
      deleteStaleConsumerGroups: false
      roundtripSla: 20s
      commitSla: 10s
```
The kminion starting log will stuck on "Starting to consume end-to-end topic"
```
{"level":"info","ts":"2021-09-01T03:01:54.085Z","logger":"main","msg":"started kminion","version":"sha-1e3a1d5ea8eedc01aaee7dbf35e23db1bff27f6a"}
{"level":"info","ts":"2021-09-01T03:01:54.086Z","logger":"main.kafka_service","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata","seed_brokers":"local-test-kminion-monitoring-service:9093"}
{"level":"info","ts":"2021-09-01T03:01:54.092Z","logger":"main.kafka_service","msg":"successfully connected to kafka cluster","advertised_broker_count":3,"topic_count":1,"controller_id":1,"kafka_version":"v2.7"}
{"level":"info","ts":"2021-09-01T03:01:54.095Z","logger":"main.kafka_service","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata","seed_brokers":"local-test-kminion-monitoring-service:9093"}
{"level":"info","ts":"2021-09-01T03:01:54.102Z","logger":"main.kafka_service","msg":"successfully connected to kafka cluster","advertised_broker_count":3,"topic_count":1,"controller_id":1,"kafka_version":"v2.7"}
{"level":"info","ts":"2021-09-01T03:01:54.108Z","logger":"main.e2e","msg":"initializing consumer and waiting until it has received the first record batch"}
{"level":"info","ts":"2021-09-01T03:01:54.108Z","logger":"main.e2e","msg":"Starting to consume end-to-end topic","topic_name":"kminion-end-to-end","group_id":"kminion-end-to-end-1cee03ee-7738-48b2-adec-41c32f5d446d"}
```
But simply change endToEnd to false, the rest of the configuration file remains unchanged, the exporter is normal start, and the starting log is as follows:
```
{"level":"info","ts":"2021-09-01T03:11:00.654Z","logger":"main","msg":"started kminion","version":"sha-1e3a1d5ea8eedc01aaee7dbf35e23db1bff27f6a"}
{"level":"info","ts":"2021-09-01T03:11:00.654Z","logger":"main.kafka_service","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata","seed_brokers":"local-test-kminion-monitoring-service:9093"}
{"level":"info","ts":"2021-09-01T03:11:00.659Z","logger":"main.kafka_service","msg":"successfully connected to kafka cluster","advertised_broker_count":3,"topic_count":1,"controller_id":1,"kafka_version":"v2.7"}
{"level":"info","ts":"2021-09-01T03:11:00.662Z","logger":"main","msg":"listening on address","listen_address":"0.0.0.0:9308"}
```
