### ISSUE TITLE
Kafka Authorization question

### ISSUE THREAD

**Issue by 0123hoang** [cloudhut/kminion#138]
I'm new with Kminion and struggling with Kafka Authorization.  
Why I only need metrics from few or none topics/few groups but kafka authorization log say Kminion need Describe ACL from all topics ? This quite annoying log file.
My compose:
```
version: "3.3"
services:
  kafka_exporter:
    image: quay.io/cloudhut/kminion:v2.2
    restart: always
    ports:
      - 9630:8080
    environment:
      - KAFKA_BROKERS=[...]
      - MINION_CONSUMERGROUPS_SCRAPEMODE=adminApi
      - MINION_CONSUMERGROUPS_GRANULARITY=topic
      - MINION_CONSUMERGROUPS_ALLOWEDGROUPS=test-consumer-group
      - MINION_TOPICS_GRANULARITY=topic
      - MINION_TOPICS_IGNOREDTOPICS=*

```
