### ISSUE TITLE
Kafka-minion pods using high memory 

### ISSUE THREAD

**Issue by yeshwanth1312** [cloudhut/kminion#67]
Hi Team , 

We are using Kafka-Minion to export metrics from our kafka-clusters . We are seeing high resource usage on kafka-minion pods , Its using Like 30G Memory and lot of CPU . these metrics are being scraped by Datadog agent . We are not sure how to reduce resource usage . Please let us know if we are missing some configuration here . If we set resource limits pods go for crash . 

```
replicaCount: 1

clusterName: ***

kafka:
  brokers: *****
#image:
#  repository: quay.io/google-cloud-tools/kafka-minion
#  tag: v1.0.1

resources:
  requests:
    cpu: 4000m
    memory: 13Gi

livenessProbe:
  initialDelaySeconds: 60
  failureThreshold: 120

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 60
  failureThreshold: 120

datadog:
  enabled: true

```

![image](https://user-images.githubusercontent.com/34922578/98274513-7f1fa080-1f61-11eb-81e1-108e64f491c8.png)
