### ISSUE TITLE
High CPU usage after broker OOMKilled

### ISSUE THREAD

**Issue by solsson** [cloudhut/kminion#83]
We're running kminion in a staging cluster with preemptible nodes, a 6-broker cluster. On two occasions in a couple of weeks we've seen kminon CPU max out.

Here kafka-1 got evicted at the first spike and kafka-5 at the secod spike:
![Screenshot from 2021-04-21 06-59-35](https://user-images.githubusercontent.com/144945/115499614-02168800-a270-11eb-80ae-47e8fb9322dd.png)

IMO the magnitude of those spikes isn't warranted by a common event like broker eviction, but they're clearly manageable. What's more worrying is the CPU use after the last event, which seems to have been kafka-0 restarting due to OOMKilled. I'm attaching logs.
[kminion-high-cpu-logs.txt.gz](https://github.com/cloudhut/kminion/files/6348209/kminion-high-cpu-logs.txt.gz)

A curious curcumstance is that we have a kminion running in a different GKE cluster connected to the same kafka brokers. The setup is identical, except that the other kminion connects using federated DNS which means a delay in discovery of podIP changes. That kminon has recovered on both occasions, and the spikes look lower:
![Screenshot from 2021-04-21 07-13-21](https://user-images.githubusercontent.com/144945/115500217-2888f300-a271-11eb-8a66-5265346204ef.png)

Broker eviction is very common in the staging cluster, and OOMKilled too has happened more than two times.

**Comment by solsson** [comment]
Our kminion setup is https://github.com/Yolean/kubernetes-kafka/tree/master/consumers-prometheus with the following override:
```
        env:
        - name: KAFKA_BROKERS
          value: >-
            kafka-0.kafka.kafka-v2.svc.cluster.local:9092,kafka-1.kafka.kafka-v2.svc.cluster.local:9092,kafka-2.kafka.kafka-v2.svc.cluster.local:9092,kafka-3.kafka.kafka-v2.svc.cluster.local:9092,kafka-4.kafka.kafka-v2.svc.cluster.local:9092,kafka-5.kafka.kafka-v2.svc.cluster.local:9092
```
