### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by PythonDanny** [cloudhut/kminion#87]
{"level":"fatal","ts":1620296288.6564505,"caller":"kminion/main.go:29","msg":"failed to parse config","error":"1 error(s) decoding:\n\n* 'kafka' expected a map, got 'slice'","stacktrace":"main.main\n\t/home/runner/work/kminion/kminion/main.go:29\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.0/x64/src/runtime/proc.go:225"}

Hi, I have problems with using v2.0+ minion. I had no issue so far with version 1 :( any idea how to get more debug info while running ? I cannot find a problem with config file/ environment variables

**Comment by weeco** [comment]
@PythonDanny Can you paste what your config looks like? Especially the config under your `kafka` key. Please compare it to the reference config: https://github.com/cloudhut/kminion/blob/master/docs/reference-config.yaml#L19

I believe there's an issue with how your config looks like.

**Comment by PythonDanny** [comment]
Hi, thanks for the reponse.
I i thought kafka key is wrong , however I cannot find a problem 
I've tried brokers: ["test01-domain.com,test02-domain.com,test03-domain.com"] (with and without ports) aswell  - using kafka brokers+sasl
yaml got validated with yamllint and ansible-lint aswell - both say its valid yaml

tried aswell with out ports brokers: [test01-domain.com,test02-domain.com,test03-domain.com]
original config.yml

kafka:
  brokers: [test01-domain.com:9092,test02-domain.com:9092,test03-domain.com:9092]
  clientId: "kminion"
  rackId: ""
  tls:
    enabled: false
    caFilepath: ""
    certFilepath: ""
    keyFilepath: ""
    passphrase: ""
    insecureSkipTlsVerify: false
  sasl:
    enabled: true
    username: "secretuser"
    password: "secretpassword"
    mechanism: "SCRAM-SHA-256"
    gssapi:
      authType: ""
      keyTabPath: ""
      kerberosConfigPath: ""
      serviceName: ""
      username: ""
      password: ""
      realm: ""

and getting  when try to run it
level":"fatal","ts":1621341844.2820017,"caller":"kminion/main.go:29","msg":"failed to parse config","error":"1 error(s) decoding:\n\n* 'kafka' expected a map, got 'slice'","stacktrace":"main.main\n\t/home/runner/work/kminion/kminion/main.go:29\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225"}

**Comment by PythonDanny** [comment]
tried this aswell without success :(
kafka: 
  brokers:
    - test01-domain.com:9092
    - test01-domain.com:9092
    - test01-domain.com:9092
 {"level":"fatal","ts":1621342735.7698393,"caller":"kminion/main.go:29","msg":"failed to parse config","error":"1 error(s) decoding:\n\n* 'kafka' expected a map, got 'slice'","stacktrace":"main.main\n\t/home/runner/work/kminion/kminion/main.go:29\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225"}


and
this one with expected exception:
kafka: 
  brokers:
    - test01-domain.com: 9092
    - test01-domain.com: 9092
    - test01-domain.com: 9092
with 
{"level":"fatal","ts":1621342726.7393641,"caller":"kminion/main.go:29","msg":"failed to parse config","error":"3 error(s) decoding:\n\n* 'kafka.brokers[0]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[cpkafka01-test-blue.cz.infra:9092]'\n* 'kafka.brokers[1]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[cpkafka02-test-blue.cz.infra:9092]'\n* 'kafka.brokers[2]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[cpkafka03-test-blue.cz.infra:9092]'","stacktrace":"main.main\n\t/home/runner/work/kminion/kminion/main.go:29\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225"}


and I've tried aswell without use of yml and used env variables
export KAFKA_BROKERS="test01-domain.com:9092,test02-domain.com:9092,test03-domain.com:9092"
again with
{"level":"fatal","ts":1621342930.776594,"caller":"kminion/main.go:29","msg":"failed to parse config","error":"1 error(s) decoding:\n\n* 'kafka' expected a map, got 'slice'","stacktrace":"main.main\n\t/home/runner/work/kminion/kminion/main.go:29\nruntime.main\n\t/opt/hostedtoolcache/go/1.16.3/x64/src/runtime/proc.go:225"}

**Comment by weeco** [comment]
Can you please post your configuration with the proper formatting in github (using tripple backticks). Otherwise the indenting gets lost and therefore I can't check what's wrong anyways.

**Comment by PythonDanny** [comment]
```
kafka:
  brokers: [test01-domain.com:9092,test02-domain.com:9092,test03-domain.com:9092]
  clientId: "kminion"
  rackId: ""
  tls:
    enabled: false
    caFilepath: ""
    certFilepath: ""
    keyFilepath: ""
    passphrase: ""
    insecureSkipTlsVerify: true
  sasl:
    enabled: true
    username: "secretadmin"
    password: "supersecretpswd"
    mechanism: "SCRAM-SHA-256"
    gssapi:
      authType: ""
      keyTabPath: ""
      kerberosConfigPath: ""
      serviceName: ""
      username: ""
      password: ""
      realm: ""

minion:
  consumerGroups:
    enabled: true
    scrapeMode: adminApi
    granularity: partition
    allowedGroups: []
    ignoredGroups: []
  topics:
    granularity: partition
    allowedTopics: []
    ignoredTopics: []
  logDirs:
    enabled: true

exporter:
  namespace: "kminion"
  host: ""
  port: 8090

logger:
  level: info
```

most recent try
filled SALS,brokers and change port from 8080 to 8090
